//
enum ENUM_ACTIVITY {
   ACTIVITY_EXECUTE = 1,
   ACTIVITY_MODIFY = 2,
   ACTIVITY_CLOSE = 4,
   ACTIVITY_DELETE = 8, 
   ACTIVITY_STATECHANGE = 16,
   ACTIVITY_NOTHING = 32,
   ACTIVITY_CUSTOM1 = 64,
   ACTIVITY_CUSTOM2 = 128,
   ACTIVITY_CUSTOM3 = 256,
};