#include "EventHandler\__classnames.mqh"
#include "OrderManager\__classnames.mqh"
#include "OrderManagerMT4\__classnames.mqh"
#include "OrderManagerMT5\__classnames.mqh"
#include "SymbolInfoMT4\__classnames.mqh"
#include "SymbolInfoMT5\__classnames.mqh"
#include "SymbolLoader\__classnames.mqh"