#include "..\Loader.mqh"
#include "..\TestManager\Loader.mqh"
#include "TestSymbolInfo.mqh"
#include "TestSymbolLoader.mqh"
#include "TestOrder.mqh"
#include "TestPointer.mqh"
#include "TestTrigger.mqh"
