//

enum ENUM_ORDERSELECT {
   ORDERSELECT_ANY,
   ORDERSELECT_MARKET,
   ORDERSELECT_PENDING,
   ORDERSELECT_LIMIT,
   ORDERSELECT_STOP,
   ORDERSELECT_BUY,
   ORDERSELECT_SELL,
   ORDERSELECT_BUYSTOP,
   ORDERSELECT_SELLSTOP,
   ORDERSELECT_BUYLIMIT,
   ORDERSELECT_SELLLIMIT,
   ORDERSELECT_LONG,
   ORDERSELECT_SHORT,
   ORDERSELECT_LONGPENDING,
   ORDERSELECT_SHORTPENDING,
   ORDERSELECT_NONE
};

