#include "TraitAppAccess.mqh"
#include "TraitLoadSymbolFunction.mqh"
#include "TraitGetType.mqh"
#include "TraitHasEvents.mqh"
#include "TraitHasCommands.mqh"
#include "TraitSendCommands.mqh"
#include "TraitNewObject.mqh"
